In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset = pd.read_csv('Bank.csv')
x = dataset.iloc[:,3:13].values # independend varible
y = dataset.iloc[:,13].values #  depend varible

In [29]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [3]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [4]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [5]:
# encoding categorial data
from sklearn.preprocessing import LabelEncoder ,OneHotEncoder 


In [6]:
labelencoder_x_1 = LabelEncoder()
x[:,1] = labelencoder_x_1.fit_transform(x[:,1])
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
labelencoder_x_2 = LabelEncoder()
x[:,2] = labelencoder_x_2.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
onehotencoder = OneHotEncoder(categorical_features =[1])
x = onehotencoder.fit_transform(x).toarray()
x

/home/wajoud/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/wajoud/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [9]:
x = x[:,1:]
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [10]:
# spliting 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)


In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [12]:
import keras
from keras.models import Sequential
from keras.layers import Dense # for layers and its connection

Using TensorFlow backend.


In [13]:
# inita ANN
classifier = Sequential()

In [14]:
# adding the imput and first hidden layer 
classifier.add(Dense(output_dim = 6 ,init ='uniform' , activation ='relu' , input_dim = 11))
#output_dim = op dimension of hidden layer 
# init =init the weights and bies (unifrom it select randon values)
# activation = recitifr linear unit(relu)

/home/wajoud/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [15]:
# add one more hidden layer 
classifier.add(Dense(output_dim = 6 ,init ='uniform' , activation ='relu'))

/home/wajoud/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [16]:
# add op layer 
classifier.add(Dense(output_dim = 1 ,init ='uniform' , activation ='sigmoid'))

/home/wajoud/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [17]:
# compiling the ANN
classifier.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics =['accuracy'])

In [18]:
# fitting the Ann to the traning set
classifier.fit(x_train,y_train,batch_size = 10 ,nb_epoch = 100)

/home/wajoud/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 5s 625us/step - loss: 0.5013 - accuracy: 0.7951
Epoch 2/100
8000/8000 [==============================] - 3s 419us/step - loss: 0.4300 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 417us/step - loss: 0.4256 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 4s 442us/step - loss: 0.4216 - accuracy: 0.7976
Epoch 5/100
8000/8000 [==============================] - 4s 505us/step - loss: 0.4196 - accuracy: 0.8181
Epoch 6/100
8000/8000 [==============================] - 3s 387us/step - loss: 0.4173 - accuracy: 0.8220
Epoch 7/100
8000/8000 [==============================] - 3s 434us/step - loss: 0.4156 - accuracy: 0.8259
Epoch 8/100
8000/8000 [==============================] - 3s 362us/step - loss: 0.4141 - accuracy: 0.8301
Epoch 9/100
8000/8000 [==============================] - 3s 371us/step - loss: 0.4128 - accuracy: 0.8313
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 4s 513us/step - loss: 0.3998 - accuracy: 0.8355
Epoch 78/100
8000/8000 [==============================] - 4s 467us/step - loss: 0.4000 - accuracy: 0.8356
Epoch 79/100
8000/8000 [==============================] - 4s 451us/step - loss: 0.3994 - accuracy: 0.8351
Epoch 80/100
8000/8000 [==============================] - 3s 365us/step - loss: 0.3998 - accuracy: 0.8356
Epoch 81/100
8000/8000 [==============================] - 3s 408us/step - loss: 0.3996 - accuracy: 0.8371
Epoch 82/100
8000/8000 [==============================] - 3s 361us/step - loss: 0.4000 - accuracy: 0.8374
Epoch 83/100
8000/8000 [==============================] - 3s 347us/step - loss: 0.4000 - accuracy: 0.8359
Epoch 84/100
8000/8000 [==============================] - 3s 410us/step - loss: 0.3995 - accuracy: 0.8366
Epoch 85/100
8000/8000 [==============================] - 3s 396us/step - loss: 0.3995 - accuracy: 0.8361
Epoch 86/100
8000/8000 [==============================] - 3

In [19]:
# predicting the test set result 
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

In [20]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[1544,   51],
       [ 262,  143]])

In [24]:
# to check the accuracy 
(1539+143)/2000

0.841

In [28]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred)*100,'%')

84.35000000000001 %
